SELECT 
	L.NAME AS 'LOCATION',
	MACHINE.NAME AS SYSTEM_NAME,
	MACHINE.IP, 
	MACHINE.MAC, 
	MACHINE.LAST_INVENTORY
FROM MACHINE
	LEFT JOIN MACHINE_LABEL_JT MLJT ON MACHINE.ID = MLJT.MACHINE_ID
	LEFT JOIN LABEL L ON MLJT.LABEL_ID = L.ID
	LEFT JOIN MACHINE_LABEL_JT ON MACHINE_LABEL_JT.MACHINE_ID = MACHINE.ID
GROUP BY MACHINE.NAME

ORDER BY L.NAME ASC, MACHINE.NAME ASC
