SELECT
  DISTINCT NAME
FROM MACHINE
  join KBSYS.KONDUCTOR_TASK KT on KT.KUID = MACHINE.KUID and KT.TYPE like 'kpatch%' and KT.PHASE ='reboot pending'
WHERE
  MACHINE.NAME NOT LIKE 'frontprefixfilterhere%'
ORDER BY MACHINE.NAME
