SELECT
  DISTINCT NAME
FROM MACHINE
  JOIN KBSYS.KONDUCTOR_TASK KT ON KT.KUID = MACHINE.KUID AND KT.TYPE LIKE 'kpatch%' AND KT.PHASE ='reboot pending'
WHERE
  MACHINE.NAME NOT LIKE 'frontprefixfilterhere%'
ORDER BY MACHINE.NAME
