SELECT 
	COUNT(M.ID) as Count
FROM ORG1.MACHINE M
JOIN MACHINE_DISKS D on M.ID = D.ID
WHERE 
	M.NAME LIKE 'SERVERPREFIXHERE%'
	and D.NAME LIKE 'Drive C:%'
	and DISK_FREE < ((RAM_TOTAL*2)/1024)
	and DISK_FREE < 30	
	and DISK_SIZE > 0
	and M.NAME <> 'ANYSERVERYOUWANTTOFILTEROUT'
ORDER BY
	DISK_FREE ASC
