SELECT 
	COUNT(M.ID) as Count
FROM ORG1.MACHINE M
JOIN MACHINE_DISKS D on M.ID = D.ID
WHERE 
	M.NAME LIKE 'SERVERPREFIXHERE%'
	AND D.NAME LIKE 'Drive C:%'
	AND DISK_FREE < ((RAM_TOTAL*2)/1024)
	AND DISK_FREE < 30	
	AND DISK_SIZE > 0
	AND M.NAME <> 'ANYSERVERYOUWANTTOFILTEROUT'
ORDER BY
	DISK_FREE ASC
