SELECT
  STR_TO_DATE((DATE_FORMAT(HD_TICKET.CREATED, '%m-1-%Y')),'%m-%d-%Y') AS time_sec,
  COUNT(HD_TICKET.ID)as Created
FROM HD_TICKET
  left join HD_QUEUE on HD_QUEUE_ID = HD_QUEUE.ID
  left join HD_CATEGORY on HD_CATEGORY_ID = HD_CATEGORY.ID
  left join HD_STATUS on HD_STATUS_ID = HD_STATUS.ID
WHERE ((HD_QUEUE.ID <> 1) AND (HD_QUEUE.ID <> 2))
GROUP BY time_sec
