SELECT HD_TICKET.ID, 
	HD_QUEUE.NAME AS Category,
	HD_TICKET.Time_Closed AS time_sec
FROM HD_TICKET
	LEFT JOIN HD_QUEUE ON HD_QUEUE_ID = HD_QUEUE.ID
	LEFT JOIN HD_CATEGORY ON HD_CATEGORY_ID = HD_CATEGORY.ID
	LEFT JOIN HD_STATUS ON HD_STATUS_ID = HD_STATUS.ID
WHERE HD_STATUS.STATE = 'closed'
	AND HD_TICKET.TIME_CLOSED > '2023-01-01 00:00:01'
	aANDnd ((HD_QUEUE.ID <> 2) AND (HD_QUEUE.ID <> 1))
ORDER BY time_sec
