SELECT
  STR_TO_DATE((DATE_FORMAT(HD_TICKET.CREATED, '%m-1-%Y')),'%m-%d-%Y') AS time_sec,
  COUNT(HD_TICKET.ID) AS Created
FROM HD_TICKET
  LEFT JOIN HD_QUEUE ON HD_QUEUE_ID = HD_QUEUE.ID
  LEFT JOIN HD_CATEGORY ON HD_CATEGORY_ID = HD_CATEGORY.ID
  LEFT JOIN HD_STATUS ON HD_STATUS_ID = HD_STATUS.ID
WHERE ((HD_QUEUE.ID <> 1)
  AND (HD_QUEUE.ID <> 2))
GROUP BY time_sec
