SELECT
  AVG(HD_TICKET.SATISFACTION_RATING) AS RATING,
  COUNT(HD_TICKET.ID) AS TICKETCOUNTS,
  ifnull((select FULL_NAME from USER where HD_TICKET.OWNER_ID = USER.ID),' Unassigned') as OWNER_NAME
FROM HD_TICKET
	left join HD_QUEUE on HD_QUEUE_ID = HD_QUEUE.ID
	left join HD_CATEGORY on HD_CATEGORY_ID = HD_CATEGORY.ID
	left join HD_STATUS on HD_STATUS_ID = HD_STATUS.ID
	left join HD_PRIORITY on HD_PRIORITY_ID = HD_PRIORITY.ID
	left join HD_IMPACT on HD_IMPACT_ID = HD_IMPACT.ID
	left join MACHINE on HD_TICKET.MACHINE_ID = MACHINE.ID
WHERE
	HD_STATUS.STATE = 'closed'
	and HD_TICKET.TIME_CLOSED > '2023-01-01 00:00:01'
	and HD_TICKET.SATISFACTION_RATING != 0
  and ((HD_QUEUE.ID <> 1) AND (HD_QUEUE.ID <> 2))
GROUP BY OWNER_NAME
ORDER BY TICKETCOUNTS DESC
