SELECT
  AVG(HD_TICKET.SATISFACTION_RATING) AS RATING,
  COUNT(HD_TICKET.ID) AS TICKETCOUNTS,
  ifnull((SELECT FULL_NAME FROM USER WHERE HD_TICKET.OWNER_ID = USER.ID),' Unassigned') AS OWNER_NAME
FROM HD_TICKET
	LEFT JOIN HD_QUEUE ON HD_QUEUE_ID = HD_QUEUE.ID
	LEFT JOIN HD_CATEGORY ON HD_CATEGORY_ID = HD_CATEGORY.ID
	LEFT JOIN HD_STATUS ON HD_STATUS_ID = HD_STATUS.ID
	LEFT JOIN HD_PRIORITY ON HD_PRIORITY_ID = HD_PRIORITY.ID
	LEFT JOIN HD_IMPACT ON HD_IMPACT_ID = HD_IMPACT.ID
	LEFT JOIN MACHINE ON HD_TICKET.MACHINE_ID = MACHINE.ID
WHERE HD_STATUS.STATE = 'closed'
	AND HD_TICKET.TIME_CLOSED > '2023-01-01 00:00:01'
	AND HD_TICKET.SATISFACTION_RATING != 0
	AND ((HD_QUEUE.ID <> 1) AND (HD_QUEUE.ID <> 2))
GROUP BY OWNER_NAME
ORDER BY TICKETCOUNTS DESC
